#!/usr/bin/env bash

subcommand=$1

# let's locate nginx configuration directory
nginx_basedir=$(dirname $(nginx -V 2>&1 | grep -o '\-\-conf-path=\(.*conf\)' | cut -d '=' -f2))
sites_available="$nginx_basedir/sites-available"
sites_enabled="$nginx_basedir/sites-enabled"

# read editor from environment or use vim as default
editor="${EDITOR:-vim}"


usage() {
    echo "nxhosts subcommand [server ...]"
    echo
}

case "$subcommand" in
    list)
        ls -1 /etc/nginx/sites-available
        ;;
    test)
        nginx -t
        ;;
    reload)
        nginx -s reload
        ;;
    enable|disable)
        shift
        for f in "$@"; do
            case "$subcommand" in
                enable)
                    ln -s "$sites_available/$f" "$sites_enabled/$f"
                    ;;
                disable)
                    rm "$sites_enabled/$f"
                    ;;
            esac
        done
        ;;
    edit|view)
        shift
        files=()
        for f in "$@"; do
            files=( "${files[@]}" "$sites_available/$f" )
        done
        case "$subcommand" in
            edit)
                dothis=$editor
                ;;
            view)
                dothis=less
                ;;
        esac
        $dothis $(printf " %s" "${files[@]}")
        ;;
    --help|-h)
        usage
        ;;
    *)
        exit 1
esac
